language: java
jdk:
  - openjdk11

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - jong9712@naver.com

before_deploy:
  - zip -r spring_deploy_test *
  - mkdir -p deploy
  - mv spring_deploy_test.zip deploy/spring_deploy_test.zip

